linters:
  enable:
    - gofmt
    - gosimple
    - errcheck
    - ineffassign
    - staticcheck
    - unused

run:
  deadline: 5m

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0